version: '3'
services:
  influxdb:
    image: "influxdb:1.8"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    networks:
      - vcc-net-secure
      
  telegraf:
    image: "telegraf:latest"
    environment:
      HOSTNAME: "telegraf-vcc-end-term-project"
    volumes:
      - ./telegraf/:/etc/telegraf/
    depends_on:
      - influxdb
    networks:
      - vcc-net-secure

  kapacitor:
    image: "kapacitor:latest"
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    networks:
      - vcc-net-secure

  chronograf:
    image: "chronograf:latest"
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/
    environment:
      TOKEN_SECRET: "eaf55bcda5330f6b8e1e421e9e00b1f3e80afc75"
      GH_CLIENT_ID: "7dc391a5f2eb5faf8997"
      GH_CLIENT_SECRET: "3fb2aa261ade4f8455074a93bbe344f8d2d5a6cd"
    ports:
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
    networks:
      - vcc-net-secure

networks:
  vcc-net-secure: