version: '3'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    # build:
    #   context: ./influxdb/
    #   dockerfile: ./Dockerfile
    image: "influxdb:1.8"
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    networks:
      - vcc-net-secure
  telegraf:
    # build:
    #   context: ./telegraf/
    #   dockerfile: ./Dockerfile
    image: "telegraf:latest"
    environment:
      HOSTNAME: "telegraf-vcc-end-term-project"
    # Telegraf requires network access to InfluxDB
    # links:
    #   - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      # - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    networks:
      - vcc-net-secure

  kapacitor:
  # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    # build:
    #   context: ./kapacitor/
    #   dockerfile: ./Dockerfile
    image: "kapacitor:latest"
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data/:/var/lib/kapacitor
      # Mount for kapacitor configuration
      - ./kapacitor/config/:/etc/kapacitor/
    # Kapacitor requires network access to Influxdb
    # links:
    #   - influxdb
    networks:
      - vcc-net-secure

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    # build:
    #   context: ./chronograf/
    #   dockerfile: ./Dockerfile
    image: "chronograf:latest"
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    # links:
    #   # Chronograf requires network access to InfluxDB and Kapacitor
    #   - influxdb
    #   - kapacitor
    environment:
      TOKEN_SECRET: "eaf55bcda5330f6b8e1e421e9e00b1f3e80afc75"
      GH_CLIENT_ID: "7dc391a5f2eb5faf8997"
      GH_CLIENT_SECRET: "3fb2aa261ade4f8455074a93bbe344f8d2d5a6cd"
      # GH_ORGS: "vcc-end-term-project-org"
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
    networks:
      - vcc-net-secure

networks:
  vcc-net-secure: